name: إنشاء ملف APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل المشروع
        uses: actions/checkout@v4

      - name: إعداد Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: تثبيت Flet
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: تثبيت Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: إعداد Flutter
        run: flutter doctor

      - name: بناء APK
        run: flutter build apk --release

      - name: رفع ملف APK
        uses: actions/upload-artifact@v4
        with:
          name: VPN-APK
          path: build/app/outputs/flutter-apk/app-release.apk
